const components = [
  { name: 'Home', link: '/home' },
  { name: 'Accordion', link: '/pages/accordion-docs' },
  { name: 'Bento', link: '/pages/bento-docs' },
  { name: 'Breadcrumb', link: '/pages/breadcrumbs-docs' },
  { name: 'Button', link: '/pages/button-docs' },
  { name: 'Card', link: '/pages/card-docs' },
  { name: 'Carousel', link: '/pages/carousel-docs' },
  { name: 'Checkbox', link: '/pages/checkbox-docs' },
  { name: 'Comment', link: '/pages/comment-docs' },
  { name: 'Dropdown', link: '/pages/dropdown-docs' },
  { name: 'Feed', link: '/pages/feed-docs' },
  { name: 'Form', link: '/pages/form-docs' },
  { name: 'Menu', link: '/pages/menu-docs' },
  { name: 'Icon', link: '/pages/icon-docs' },
  { name: 'Input', link: '/pages/input-docs' },
  { name: 'Loader', link: '/pages/loader-docs' },
  { name: 'Modal', link: '/pages/modal-docs' },
  { name: 'Notification', link: '/pages/notification-docs' },
  { name: 'Pagination', link: '/pages/pagination-docs' },
  { name: 'Picker', link: '/pages/picker-docs' },
  { name: 'Progress Bar', link: '/pages/progress-bar-docs' },
  { name: 'Radio Buttons', link: '/pages/radio-docs' },
  { name: 'Search Field', link: '/pages/search-docs' },
  { name: 'Slider', link: '/pages/slider-docs' },
  { name: 'Stepper', link: '/pages/stepper-docs' },
  { name: 'Tags', link: '/pages/tags-docs' },
  { name: 'Tabs', link: '/pages/tabs-docs' },
  { name: 'Tab Bar', link: '/pages/tab-bar-docs' },
  { name: 'Tooltip', link: '/pages/tooltip-docs' },
  { name: 'Toggle', link: '/pages/toggle-docs' }
];

export default components;
